// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, input, status, error, pages_crawled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, input, status, error, pages_crawled, created_at, updated_at
`

type CreateJobParams struct {
	ID           pgtype.UUID        `json:"id"`
	Input        []byte             `json:"input"`
	Status       string             `json:"status"`
	Error        pgtype.Text        `json:"error"`
	PagesCrawled int32              `json:"pages_crawled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Input,
		arg.Status,
		arg.Error,
		arg.PagesCrawled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Input,
		&i.Status,
		&i.Error,
		&i.PagesCrawled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, input, status, error, pages_crawled, created_at, updated_at FROM jobs
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Input,
			&i.Status,
			&i.Error,
			&i.PagesCrawled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, input, status, error, pages_crawled, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Input,
		&i.Status,
		&i.Error,
		&i.PagesCrawled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryIncrementPagesCrawled = `-- name: TryIncrementPagesCrawled :one
UPDATE jobs SET pages_crawled = pages_crawled + 1, updated_at = NOW()
WHERE id = $1 AND pages_crawled < $2 RETURNING id, input, status, error, pages_crawled, created_at, updated_at
`

type TryIncrementPagesCrawledParams struct {
	ID       pgtype.UUID `json:"id"`
	MaxPages int32       `json:"max_pages"`
}

func (q *Queries) TryIncrementPagesCrawled(ctx context.Context, arg TryIncrementPagesCrawledParams) (Job, error) {
	row := q.db.QueryRow(ctx, tryIncrementPagesCrawled, arg.ID, arg.MaxPages)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Input,
		&i.Status,
		&i.Error,
		&i.PagesCrawled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = $1, error = $2, updated_at = NOW() WHERE id = $3 RETURNING id, input, status, error, pages_crawled, created_at, updated_at
`

type UpdateJobStatusParams struct {
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.Status, arg.Error, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Input,
		&i.Status,
		&i.Error,
		&i.PagesCrawled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
