// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	Input        []byte             `json:"input"`
	Status       string             `json:"status"`
	Error        pgtype.Text        `json:"error"`
	PagesCrawled int32              `json:"pages_crawled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Page struct {
	ID          int32              `json:"id"`
	JobID       pgtype.UUID        `json:"job_id"`
	Url         string             `json:"url"`
	Title       pgtype.Text        `json:"title"`
	Html        string             `json:"html"`
	TextContent string             `json:"text_content"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}
