// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPagesByJobID = `-- name: GetPagesByJobID :many
SELECT id, job_id, url, title, html, text_content, fetched_at FROM pages WHERE job_id = $1
`

func (q *Queries) GetPagesByJobID(ctx context.Context, jobID pgtype.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, getPagesByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Url,
			&i.Title,
			&i.Html,
			&i.TextContent,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForIndex = `-- name: ListPagesForIndex :many
SELECT id,title, text_content FROM pages
`

type ListPagesForIndexRow struct {
	ID          int32       `json:"id"`
	Title       pgtype.Text `json:"title"`
	TextContent string      `json:"text_content"`
}

func (q *Queries) ListPagesForIndex(ctx context.Context) ([]ListPagesForIndexRow, error) {
	rows, err := q.db.Query(ctx, listPagesForIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPagesForIndexRow
	for rows.Next() {
		var i ListPagesForIndexRow
		if err := rows.Scan(&i.ID, &i.Title, &i.TextContent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :one
INSERT INTO pages (job_id, url, title, html, text_content)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (url) DO UPDATE SET
job_id = EXCLUDED.job_id,
title = EXCLUDED.title,
html = EXCLUDED.html,
text_content = EXCLUDED.text_content,
fetched_at = NOW()
RETURNING id, job_id, url, title, html, text_content, fetched_at
`

type UpsertPageParams struct {
	JobID       pgtype.UUID `json:"job_id"`
	Url         string      `json:"url"`
	Title       pgtype.Text `json:"title"`
	Html        string      `json:"html"`
	TextContent string      `json:"text_content"`
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, upsertPage,
		arg.JobID,
		arg.Url,
		arg.Title,
		arg.Html,
		arg.TextContent,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Url,
		&i.Title,
		&i.Html,
		&i.TextContent,
		&i.FetchedAt,
	)
	return i, err
}
