// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	GetAllJobs(ctx context.Context) ([]Job, error)
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	GetPagesByJobID(ctx context.Context, jobID pgtype.UUID) ([]Page, error)
	TryIncrementPagesCrawled(ctx context.Context, arg TryIncrementPagesCrawledParams) (Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpsertPage(ctx context.Context, arg UpsertPageParams) (Page, error)
}

var _ Querier = (*Queries)(nil)
